# Modules

import os
import time
import datetime

# Variables

start = 0
user = 0
user2 = 0
user2_1 = 0
user3 = 0
user3_1 = 0
x = 0
y = 0
events = 0
today = datetime.date.today()

if today.day == 23 and today.month == 8:
    events = "DoubleXP"
else:
    events = 0

# Startup Sequence

print("AquaVeeru Games & Media")
time.sleep(3)
os.system('cls')
print("Quest to Mount Embercrest")
print("    ╰─❨✧✧❩─╯     ")
print("")
print("v1.2 Demo/Concept Edition (Made by AquaVeeru)")
print("")
print("1 ➼ Play")
print("2 ➼ Credits")
print("3 ➼ Mod Info")
print("4 ➼ Event Tracker")
print("5 ➼ Exit")

start = int(input("Option (1/2/3/4) = "))

# Conditions

if start == 2 :
    os.system('cls')
    print("SPECIAL THANKS TO:")
    print("")
    print("Vru (Aquaveeru) for creating the game")
    print("")
    print("AlphaMole (qmole) for beta testing")
    print("")
    time.sleep(2)
    print("To head back to main menu, restart program")
    time.sleep(10)
if start == 3 :
    os.system('cls')
    print("How to mod the game (Windows Only, Requires Python, pip & PyInstaller)")
    print("")
    print("1 - Download source.py from the GitHub")
    print("2 - Open source.py with a compiler such as IDLE, VScode or Notepad++")
    print("3 - Using the compiler you can modify the code with Python")
    print("4 - After your mod is done, convert the file into an .exe file using PyInstaller")
    print("5 - You're all set! You can now publish your mod.")
    print("")
    print("Tip: For the Mod info option, you can add specific information about your mod.")
    print("")
    print("To go back to main menu, restart program.")
    time.sleep(20)
    exit()
if start == 4 :
    os.system('cls')
    print("Events:")
    print("")
    if events == 0 :
        print("There are no Events available at this time.")
        print("")
        print("To go back to main menu, restart program.")
    if events == "DoubleXP" :
        print("Double XP Day!")
        print("")
        print("To go back to main menu, restart program.")
    time.sleep(20)
    exit()
if start == 5 :
    os.system('cls')
    print("Exiting Demo")
    time.sleep(2)
    exit()
elif start == 1 :
    os.system('cls')
    print("Welcome Samurai, to Mount Celestia!")
    time.sleep(2)
    print("You are here, because you have been assigned with a quest to head off to Grayspires")
    time.sleep(1)
    print("A Village on Mount Embercrest.")
    time.sleep(2)
    print("To get there, you will have to climb multiple mountains and pass many villages.")
    time.sleep(2)
    os.system('cls')
    print("Alright! Time to head off to our first location, Oakhaven on Arkham's Peak.")
    time.sleep(2)
    print("Note that everytime you kill an enemy or a boss, you level up by 1")
    time.sleep(2)
    os.system('cls')
    print("You encounter a Zombie (lvl. 1)")
    time.sleep(1)
    print("")
    print("1 ➼ Use Sword")
    print("2 ➼ Use Bow")
    print("")
    user1 = int(input("Option: "))
    if user1 == 1 :
        os.system('cls')
        print("You slice the Zombie in half! You are now level 2.")
        time.sleep(2)
        print("You continue on with your journey to Arkham's Peak.")
        time.sleep(2)
        os.system('cls')
        print("You stumble upon two paths, one leads to the forest of the Tundra, the other leads to a cave.")
        print("")
        time.sleep(1)
        print("1 ➼ Forest")
        print("2 ➼ Cave")
        print("")
        user2_1 = int(input("What path will you take? "))
        if user2_1 == 2 :
            # Cave
            os.system('cls')
            print("You decide to go through the cave, and you encounter a Stone Golem (lvl. 1)")
            print("")
            time.sleep(1)
            print("1 ➼ Use Sword")
            print("2 ➼ Use Bow")
            user3_1 = int(input("Option: "))
            if user3_1 == 1 :
                os.system('cls')
                print("You use your Sword to slice the Golem, your sword is slightly damaged though.")
                time.sleep(2)
                print("After a bit of exploring in the cave, you see a light at the top.")
                time.sleep(2)
                os.system('cls')
                print("You've made it to Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
            if user3_1 == 2 :
                os.system('cls')
                print("You use your Bow to Shoot the Golem, your Arrow got damaged though.")
                time.sleep(2)
                print("After a bit of exploring in the cave, you see a light at the top.")
                time.sleep(2)
                os.system('cls')
                print("You've made it to Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
        if user2_1 == 1 :
            os.system('cls')
            print("You decide to go through the forest, and you encounter a Forest Sorcerer (lvl. 1)")
            print("")
            time.sleep(1)
            print("1 ➼ Use Sword")
            print("2 ➼ Use Bow")
            y = int(input("Option: "))
            if y == 1 :
                os.system('cls')
                print("You Slice the Sorcerer, and continue your journey through the forest.")
                time.sleep(2)
                print("You see a Mountain and a Village in the distance, you run over to it.")
                time.sleep(2)
                os.system('cls')
                print("You've reached Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
            if y == 2 :
                os.system('cls')
                print("You Shoot the Sorcerer, and continue your journey through the forest.")
                time.sleep(2)
                print("You see a Mountain and a Village in the distance, you run over to it.")
                time.sleep(2)
                os.system('cls')
                print("You've reached Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
    elif user1 == 2 :
        os.system('cls')
        print("You use your Bow to shoot the zombie and you gain a level!")
        time.sleep(2)
        print("You continue on with your journey to Arkham's Peak.")
        time.sleep(2)
        os.system('cls')
        print("You stumble upon two paths, one leads to the forest of the Tundra, the other leads to a cave.")
        print("")
        time.sleep(1)
        print("1 ➼ Forest")
        print("2 ➼ Cave")
        print("")
        user2 = int(input("What path will you take? "))
        if user2 == 2 :
            os.system('cls')
            print("You decide to go through the cave, and you encounter a Stone Golem (lvl. 1)")
            print("")
            time.sleep(1)
            print("1 ➼ Use Sword")
            print("2 ➼ Use Bow")
            x = int(input("Option: "))
            if x == 1 :
                os.system('cls')
                print("You use your Sword to slice the Golem, your sword is slightly damaged though.")
                time.sleep(2)
                print("After a bit of exploring in the cave, you see a light at the top.")
                time.sleep(2)
                os.system('cls')
                print("You've made it to Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
            if x == 2 :
                os.system('cls')
                print("You use your Bow to Shoot the Golem, your Arrow got damaged though.")
                time.sleep(2)
                print("After a bit of exploring in the cave, you see a light at the top.")
                time.sleep(2)
                os.system('cls')
                print("You've made it to Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
        if user2 == 1 :
            # Forest
            os.system('cls')
            print("You decide to go through the forest, and you encounter a Forest Sorcerer (lvl. 1)")
            print("")
            time.sleep(1)
            print("1 ➼ Use Sword")
            print("2 ➼ Use Bow")
            user3 = int(input("Option: "))
            if user3 == 1 :
                os.system('cls')
                print("You Slice the Sorcerer, and continue your journey through the forest.")
                time.sleep(2)
                print("You see a Mountain and a Village in the distance, you run over to it.")
                time.sleep(2)
                os.system('cls')
                print("You've reached Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
            if user3 == 2 :
                os.system('cls')
                print("You Shoot the Sorcerer, and continue your journey through the forest.")
                time.sleep(2)
                print("You see a Mountain and a Village in the distance, you run over to it.")
                time.sleep(2)
                os.system('cls')
                print("You've reached Oakhaven!")
                time.sleep(1)
                print("")
                print("Objective Complete! 10 XP")
                time.sleep(3)
                os.system('cls')
                print("Demo Complete!")
                print("")
                print("Thanks a lot for playing the demo.")
                time.sleep(10)
                exit()
    
